version: "3"

services:
  user-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bootleg
      - MYSQL_DATABASE=users
    volumes:
      - ./data/userdb:/var/lib/mysql
      - ./bootleg-ebay/users/db/sqlfile.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3307:3306

  advertisement-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bootleg
      - MYSQL_DATABASE=advertisements
    volumes:
      - ./data/advertisementdb:/var/lib/mysql
      - ./bootleg-ebay/advertisements/db/sqlfile.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3308:3306

  item-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/itemsdb:/data/db

  itemdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@item-db:27017/

  notif-db:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/notifsdb:/data/db

  notifdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@notif-db:27017/

  auctions-db:
    image: mongo:latest
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/auctionsdb:/data/db

  auctions-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@auctions-db:27017/

  checkout-db:
    image: "redis:alpine"

    command: redis-server --requirepass bootleg

    ports:
      - "6379:6379"

    volumes:
      - ./data/checkoutdb/redis-data:/var/lib/redis
      - ./data/checkoutdb/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
