version: "3"

services:
  users-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bootleg
      - MYSQL_DATABASE=users
    volumes:
      - ./data/users-db:/var/lib/mysql
      - ./bootleg-ebay/users/db/sqlfile.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3307:3306

  advertisements-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bootleg
      - MYSQL_DATABASE=advertisements
    volumes:
      - ./data/advertisements-db:/var/lib/mysql
      - ./bootleg-ebay/advertisements/db/sqlfile.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3308:3306

  items-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bootleg
    volumes:
      - ./data/items-db:/data/db

  items-db-mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - items-db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: bootleg
      ME_CONFIG_MONGODB_URL: mongodb://root:bootleg@items-db:27017/

  notifs-db:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bootleg
    volumes:
      - ./data/notifs-db:/data/db

  notifs-db-mongo-express:
    image: mongo-express
    depends_on:
      - notifs-db
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: bootleg
      ME_CONFIG_MONGODB_URL: mongodb://root:bootleg@notifs-db:27017/

  auctions-db:
    image: mongo:latest
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bootleg
    volumes:
      - ./data/auctions-db:/data/db

  auctions-db-mongo-express:
    image: mongo-express
    depends_on:
      - auctions-db
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: bootleg
      ME_CONFIG_MONGODB_URL: mongodb://root:bootleg@auctions-db:27017/

  carts-db:
    image: "redis:alpine"
    command: redis-server --requirepass bootleg
    ports:
      - "6379:6379"
    volumes:
      - ./data/carts-db/redis-data:/var/lib/redis
      - ./data/carts-db/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
