import os

CARTS_SERVICE_HOST = os.getenv('CARTSAPIHOST', "localhost")
CARTS_PORT = ":3211"

ITEMS_SERVICE_HOST = os.getenv('ITEMSAPIHOST', "localhost")
ITEMS_PORT = ":8099"

USERS_SERVICE_HOST = os.getenv('USERAPIHOST', "localhost")
USERS_PORT = ':1001'
USERS_URL = "http://" + USERS_SERVICE_HOST + USERS_PORT

AUCTIONS_SERVICE_HOST = os.getenv('AUCTIONSAPIHOST', "localhost")
AUCTIONS_PORT = ':2222'
AUCTIONS_URL = "http://" + AUCTIONS_SERVICE_HOST + AUCTIONS_PORT

PAYMENTS_SERVICE_HOST = os.getenv('PAYMENTSAPIHOST', "localhost")
PAYMENTS_PORT = ':1003'
PAYMENTS_URL = "http://" + PAYMENTS_SERVICE_HOST + PAYMENTS_PORT

NOTIFS_SERVICE_HOST = os.getenv('NOTIFSAPIHOST', 'localhost')
NOTIFS_PORT = ':8012'